# Generated by Django 3.2.8 on 2021-10-09 05:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaptura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtendida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('descripcion', models.TextField(default='')),
            ],
        ),
    ]
