# Generated by Django 3.2.8 on 2021-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocaptura', '0002_areaatendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('bache', 'Bache'), ('falta_alumbrado', 'Falta de alumbrado'), ('semaforo', 'Falla de semaforo'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
